spring:
  server:
    port: ${PORT:8070}
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  cloud:
    stream:
      bindings:
        output:
          destination: message-out
        input:
          destination: message-in
      rabbit:
        bindings:
          output:
            producer:
              exchange-type: direct
              routing-key-expression: '"#"'
          input:
            consumer:
              exchange-type: direct

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

properties:
  example: Ejemplo2
  