spring:
  server:
    port: ${PORT:8080}
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'

properties:
  example: Ejemplo1
  