server:
  port: ${PORT:8080}

spring:  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  cloud:
    stream:
      bindings:
        output:
          destination: message-in
        input:
          destination: message-out
      rabbit:
        bindings:
          output:
            producer:
              exchange-type: direct
              routing-key-expression: '"#"'
          input:
            consumer:
              exchange-type: direct

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

swagger:
  title: Microservice One Tittle
  description: Microservice Description
  version: 1.0.0
  contact: 
    name: AutorName
    email: autormail@mail.com
  service:
    name: Microservice One

management:
  endpoints:
    web:
      exposure:
        include: '*'