server:
  port: ${PORT:8080}

spring:  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  cloud:
    stream:
      bindings:
        input:
          destination: message.e
        custom-message-channel:
          destination: custom-message.e
          group: custom-message.q
      rabbit:
        bindings:
          input:
            consumer:
              routing-key-expression: '"#"'
          custom-message-channel:
            consumer:
              binding-routing-key: my-routing#

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

swagger:
  title: Microservice One Tittle
  description: Microservice Description
  version: 1.0.0
  contact: 
    name: AutorName
    email: autormail@mail.com
  service:
    name: Microservice One